#!/bin/bash


#wifibang    -    wifi attacks suite
#Copyright © 2018 Leviathan36 

# This file is part of wifibang.

#	wifibang is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	wifibang is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with wifibang.  If not, see <http://www.gnu.org/licenses/>.



####################################################
                   	#SETUP#
####################################################

#make scripts executable
sudo chmod +x ./scripts/*

#add folders
[[ -d ./scripts/handshakes ]] || mkdir ./scripts/handshakes
[[ -d ./scripts/wordlists ]] || mkdir ./scripts/wordlists
[[ -d ./scripts/router_passwords ]] || mkdir ./scripts/router_passwords
[[ -d ./scripts/user_hydra ]] || mkdir ./scripts/user_hydra


!!!!!!!!!!!!!!!!!!!!!!! IF DIRECTORY NAME CONTAINS SPACES IT RETURN ERROR !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#add PATH
echo 'if directory name contains spaces the script could not work'

echo "PATH=\"\$PATH:`pwd`/scripts\"" >> $HOME/.profile
echo "export PATH" >> $HOME/.profile

echo 'RESTART SYSTEM TO UPDATE ...'

################## END SETUP #######################
