#!/bin/bash


#wifibang    -    wifi attacks suite
#Copyright © 2018 Leviathan36 

# This file is part of wifibang.

#	wifibang is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	wifibang is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with wifibang.  If not, see <http://www.gnu.org/licenses/>.



####################################################
                    #MAC_SPOOF#
####################################################

wifi_int=$1

clear

sudo ifconfig $wifi_int down || { echo "ERROR: $wifi_int"; exit 1; }

sudo macchanger -A -r $wifi_int || { echo "ERROR: $wifi_int"; exit 1; }

sudo ifconfig $wifi_int up || { echo "ERROR: $wifi_int"; exit 1; }

exit 0
    
############### END MAC_SPOOF ######################
