#!/bin/bash


#wifibang    -    wifi attacks suite
#Copyright © 2018 Leviathan36 

# This file is part of wifibang.

#	wifibang is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.

#	wifibang is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with wifibang.  If not, see <http://www.gnu.org/licenses/>.



####################################################
                    #TX POWER#
####################################################
               
               #### NOT TESTED ####
               ## 30dBm it's illegal power in several country
               
wifi_int=$1

clear
echo #formatting op
echo "!!!DANGER!!!"
echo #formatting op
echo "WOULD INCREASE TX POWER (30dBm)? [y/n]:"
echo #formatting op
printf ">>> "
read choice

while [[ "$choice" != 'y' && "$choice" != 'n' ]]; do
     echo "INSERT VALID CHARACTER [y/n]:"
     read choice
done

if [[ "$choice" == 'y' ]]     
     then sudo ifconfig $wifi_int down || { echo "ERROR: $wifi_int"; exit 1; }
                    
          sudo iw reg set BO || { echo "ERROR: can't set reg (tx power)"; exit 1; }
          
          sudo ifconfig $wifi_int up || { echo "ERROR: $wifi_int"; exit 1; }
                    
          sudo iwconfig $wifi_int txpower 30 || { echo "ERROR: can't increase power on wifi-card"; exit 1; }
          
          echo "WARNING: txpower set to 30dBm !"
fi

exit 0
     
################ END TX POWER ######################
